server:
  port: 8184

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.newegg.ec.tool.dao
  configuration:
    # user_name -> userName
    map-underscore-to-camel-case: true

backend:
  monitor: 0 */1 * * * ?

alarm:
  notify:
    wechat:
      # company ID
      corpId:
      # users: default @all
      appList:
      - appName: HierarchyService
        agentId: 1000003
        corpSecret: _jUmcToZW--dPQeeGq3TrBD34
        users:
      - appName: ItemService
        agentId: 1000002
        corpSecret: -PJ0oz3ePsk9zqndiDVgQyQPgk0
        users:
    rocketchat:
        token: -8Nt7c_lkiA-QFakZER6m09T1m4lYL-oQyHPp1jAbPC
        userID: jAmcTfGvSzWoBzD7Q
