server:
  port: 8184

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.newegg.ec.tool.dao
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true


alarm:
  notify:
    wechat:
      # 企业ID
      corpId:
      # users: 不填则默认 @all
      appList:
      - appName: HierarchyService
        agentId: 1000003
        corpSecret:
        users:
      - appName: ItemService
        agentId: 1000002
        corpSecret:
        users:
    rocketchat: