server:
  port: 8184

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.newegg.ec.tool.dao
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true


alarm:
  notify:
    wechat:
      # 企业ID
      corpId: ww0f00cb4440ed3cf1
      # users: 不填则默认 @all
      appList:
      - appName: HierarchyService
        agentId: 1000003
        corpSecret: _jUmcToZW-0BnJE9nAT4huTatCfn-dPQeeGq3TrBD34
        users:
      - appName: ItemService
        agentId: 1000002
        corpSecret: Gd55K7N0q2WGEMob-PJ0oz3ePsk9zqndiDVgQyQPgk0
        users:
    rocketchat: